library(KernSmooth)
library(MASS)
library(locpol)
data1<-data(Abalone)
Abalone<-data1[c(1:100),]
x<-Abalone$diameter
Y<-Abalone$Rings
xurut<-sort(x)
h1=regCVBwSelC(x,y,1,kernel=CosK)
h1
estimasiLoclin=locCteSmootherC(x,y,xurut,h,kernel=CosK)
yduga=estimasiLoclin[,2]
yduga
MSE=((sum(y-yduga)^2)/100)
MSE
plot(x,y)
lines(xurut,yduga)
estimasiLoclin
beta1=estimasiLoclin[,3]
plot(x,beta1)